### ISSUE TITLE
de-clutter console output

### ISSUE THREAD

**Issue by ben-bay** [LLNL/maestrowf#248]
Just to run `hello_world`, this seems like a little much:

```
(venv_maestro) geralt:maestrowf bay1$ maestro run samples/hello_world/hello_world.yaml
2020-04-14 14:22:00,313 - maestrowf.maestro:main:409 - INFO - INFO Logging Level -- Enabled
2020-04-14 14:22:00,313 - maestrowf.maestro:main:410 - WARNING - WARNING Logging Level -- Enabled
2020-04-14 14:22:00,313 - maestrowf.maestro:main:411 - CRITICAL - CRITICAL Logging Level -- Enabled
2020-04-14 14:22:00,313 - maestrowf.datastructures.yamlspecification:load_specification:104 - INFO - Loading specification -- path = samples/hello_world/hello_world.yaml
2020-04-14 14:22:00,316 - maestrowf.utils:create_parentdir:102 - INFO - Directory does not exist. Creating directories to /Users/bay1/maestrowf/sample_output/hello_world/hello_world_20200414-142200/logs
2020-04-14 14:22:00,316 - maestrowf.datastructures.core.study:__init__:199 - INFO - OUTPUT_PATH = /Users/bay1/maestrowf/sample_output/hello_world/hello_world_20200414-142200
2020-04-14 14:22:00,317 - maestrowf.datastructures.core.study:add_step:340 - INFO - Adding step 'hello_world' to study 'hello_world'...
2020-04-14 14:22:00,317 - maestrowf.datastructures.core.study:setup_workspace:379 - INFO - Setting up study workspace in '/Users/bay1/maestrowf/sample_output/hello_world/hello_world_20200414-142200'
2020-04-14 14:22:00,317 - maestrowf.datastructures.core.study:setup_environment:389 - INFO - Environment is setting up.
2020-04-14 14:22:00,317 - maestrowf.datastructures.core.studyenvironment:acquire_environment:191 - INFO - Acquiring dependencies
2020-04-14 14:22:00,317 - maestrowf.datastructures.core.study:configure_study:427 - INFO -
------------------------------------------
Output path =               /Users/bay1/maestrowf/sample_output/hello_world/hello_world_20200414-142200
Submission attempts =       1
Submission restart limit =  1
Submission throttle limit = 0
Use temporary directory =   False
Hash workspaces =           False
------------------------------------------
```

I think a lot of this could either be moved to the DEBUG logger level. At least the INFO level could be formatted to hide details such as the module's name and line.

**Comment by FrankD412** [comment]
While testing #243, I found that the errors from validation are being printed twice. I think they're being logged in both the library and the main Maestro call, but it also might be that `raise` automatically pushes a stdout/stderr message so it gets duplicated. I think that also falls into the scope of this ticket.

A sample of the problem:
```
maestro run ./samples/hello_world/hello_world\ copy.yaml
2020-04-16 08:41:54,202 - maestrowf.maestro:main:409 - INFO - INFO Logging Level -- Enabled
2020-04-16 08:41:54,202 - maestrowf.maestro:main:410 - WARNING - WARNING Logging Level -- Enabled
2020-04-16 08:41:54,202 - maestrowf.maestro:main:411 - CRITICAL - CRITICAL Logging Level -- Enabled
2020-04-16 08:41:54,202 - maestrowf.datastructures.yamlspecification:load_specification:104 - INFO - Loading specification -- path = ./samples/hello_world/hello_world copy.yaml
2020-04-16 08:41:54,210 - maestrowf.datastructures.yamlspecification:validate_schema:411 - ERROR - ("WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.",)
Traceback (most recent call last):
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 396, in validate_schema
    raise ValueError("WARNING: Unrecognized key '{0}' found in spec section '{1}'.".format(unrecognized, parent_key))
ValueError: WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.
2020-04-16 08:41:54,211 - maestrowf.datastructures.yamlspecification:_verify_steps:320 - ERROR - ("WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.",)
Traceback (most recent call last):
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 317, in _verify_steps
    YAMLSpecification.validate_schema("study.{}".format(step["name"]), step, schemas["STUDY_STEP_SCHEMA"])
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 396, in validate_schema
    raise ValueError("WARNING: Unrecognized key '{0}' found in spec section '{1}'.".format(unrecognized, parent_key))
ValueError: WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.
2020-04-16 08:41:54,211 - maestrowf.datastructures.yamlspecification:verify_study:304 - ERROR - ("WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.",)
Traceback (most recent call last):
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 301, in verify_study
    self._verify_steps()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 317, in _verify_steps
    YAMLSpecification.validate_schema("study.{}".format(step["name"]), step, schemas["STUDY_STEP_SCHEMA"])
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 396, in validate_schema
    raise ValueError("WARNING: Unrecognized key '{0}' found in spec section '{1}'.".format(unrecognized, parent_key))
ValueError: WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.
2020-04-16 08:41:54,211 - maestrowf.datastructures.yamlspecification:load_specification:111 - ERROR - ("WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.",)
Traceback (most recent call last):
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 108, in load_specification
    specification = cls.load_specification_from_stream(data)
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 151, in load_specification_from_stream
    specification.verify()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 158, in verify
    self.verify_study()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 301, in verify_study
    self._verify_steps()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 317, in _verify_steps
    YAMLSpecification.validate_schema("study.{}".format(step["name"]), step, schemas["STUDY_STEP_SCHEMA"])
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 396, in validate_schema
    raise ValueError("WARNING: Unrecognized key '{0}' found in spec section '{1}'.".format(unrecognized, parent_key))
ValueError: WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.
Traceback (most recent call last):
  File "/home/frank/.virtualenvs/py3/bin/maestro", line 11, in <module>
    load_entry_point('maestrowf', 'console_scripts', 'maestro')()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/maestro.py", line 414, in main
    rc = args.func(args)
  File "/mnt/f/Code/Python/maestrowf/maestrowf/maestro.py", line 127, in run_study
    spec = YAMLSpecification.load_specification(args.specification)
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 112, in load_specification
    raise e
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 108, in load_specification
    specification = cls.load_specification_from_stream(data)
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 151, in load_specification_from_stream
    specification.verify()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 158, in verify
    self.verify_study()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 301, in verify_study
    self._verify_steps()
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 317, in _verify_steps
    YAMLSpecification.validate_schema("study.{}".format(step["name"]), step, schemas["STUDY_STEP_SCHEMA"])
  File "/mnt/f/Code/Python/maestrowf/maestrowf/datastructures/yamlspecification.py", line 396, in validate_schema
    raise ValueError("WARNING: Unrecognized key '{0}' found in spec section '{1}'.".format(unrecognized, parent_key))
ValueError: WARNING: Unrecognized key 'frank_key' found in spec section 'study.hello_world'.
```
