### ISSUE TITLE
variables in run section of study

### ISSUE THREAD

**Issue by Jmast** [LLNL/maestrowf#274]
the spec validation seems to be applied before variable substitution is performed.

```
mast2@surface86:~/tmp$ maestro --version
maestro 1.1.7

maestro run maestro_error.yaml --dry -o test

[2020-05-21 12:00:07: ERROR] ("Value '$(NUM_GPUS)' in spec section 'study.hello' must be of type 'integer'.", <unset>, (), None, (), <unset>, <unset>, <unset>, (), None)
Traceback (most recent call last):
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 112, in load_specification
    specification = cls.load_specification_from_stream(data)
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 155, in load_specification_from_stream
    specification.verify()
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 163, in verify
    self.verify_study()
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 302, in verify_study
    self._verify_steps()
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 321, in _verify_steps
    schemas["STUDY_STEP"],
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf/datastructures/yamlspecification.py", line 432, in validate_schema
    .format(bad_val, parent_key, expected_type)
jsonschema.exceptions.ValidationError: Value '$(NUM_GPUS)' in spec section 'study.hello' must be of type 'integer'.
[2020-05-21 12:00:07: ERROR] Value '$(NUM_GPUS)' in spec section 'study.hello' must be of type 'integer'.
```

maestro_error.yaml:
```yaml

description:
    name: error_example
    description: Example of int required for value error

batch:
    bank: baasic
    host: surface
    nodes: 4
    queue: pbatch
    type: slurm

env:
    variables:
        NUM_GPUS: 2

study:
    - description: error
      name: hello
      run:
          cmd: |
            $(LAUNCHER) echo "hello"
          nodes: 2
          cores per task: 4
          gpus: $(NUM_GPUS)

```

**Comment by FrankD412** [comment]
After talking with @ben-bay, this exposes a bug. I suspect that this had worked in previous versions of Maestro because parameters could be used in keys like `procs` and `nodes` to perform scaling studies and other similar things. I've removed the enhancement label, since this no longer classifies as an enhancement as it actually is a showstopping bug. The same thing happens when applying a parameter as seen below:

```
description:
    name: error_example
    description: Example of int required for value error

batch:
    bank: baasic
    host: surface
    nodes: 4
    queue: pbatch
    type: slurm

study:
    - description: error
      name: hello
      run:
          cmd: |
            $(LAUNCHER) echo "hello"
          nodes: 2
          cores per task: 4
          gpus: $(NUM_GPUS)

global.parameters:
  NUM_GPUS:
    values: [1, 2, 3]
    label: GPUS.%%
```

**Comment by FrankD412** [comment]
@Jmast -- just wanted to tag you, but PR #279 will be fixing this. If you'd like to give it a shot ahead of time, go ahead and pull the fork and give it a shot.
