### ISSUE TITLE
Unicode hashing error

### ISSUE THREAD

**Issue by kallman2** [LLNL/maestrowf#291]
Traceback (most recent call last):
  File "3.6-maestro_dev/bin/maestro", line 11, in <module>
    load_entry_point('maestrowf', 'console_scripts', 'maestro')()
  File "tools/maestrowf_dev/maestrowf/maestro.py", line 430, in main
    rc = args.func(args)
  File "tools/maestrowf_dev/maestrowf/maestro.py", line 274, in run_study
    conductor.initialize(batch, sleeptime)
  File "tools/maestrowf_dev/maestrowf/conductor.py", line 303, in initialize
    self._pkl_path, self._exec_dag = self._study.stage()
  File "tools/maestrowf_dev/maestrowf/datastructures/core/study.py", line 853, in stage
    return self._out_path, self._stage(dag)
  File "tools/maestrowf_dev/maestrowf/datastructures/core/study.py", line 634, in _stage
    *[step, md5(combo_str).hexdigest()])
TypeError: Unicode-objects must be encoded before hashing

**Comment by kallman2** [comment]
Trying to hash parameter names: using a directory as a parameter

**Comment by FrankD412** [comment]
So this actually raised a bigger issue -- it seems that the hashing isn't applied to the script name that gets generated. The lack of hashing in the naming would result in bad/dangerous naming if a parameter is a path also. In order to make sure the names are safe, I'm considering just hashing the script name before applying the extension. Does that seem reasonable? @kallman2 @jsemler @jwhite242

**Comment by jwhite242** [comment]
Having it consistent with the hashed workspace name sounds like a good plan to me

**Comment by kallman2** [comment]
@FrankD412 Small additional request - Logger.debug does not print out the workspace if hashing. Request debug log of full name and nickname if hashing. Thanks!
