### ISSUE TITLE
walltime key missing from study run results in cryptic error message

### ISSUE THREAD

**Issue by Jmast** [LLNL/maestrowf#334]
If walltime key is missing from the study run step, it should either fail the spec validation or indicate the key is missing.

2020-12-15 09:17:07,295 - maestrowf.datastructures.core.executiongraph:_execute_record:559 - INFO - Attempting submission of 'create_sdf' (attempt 1 of 1)...
2020-12-15 09:17:07,301 - maestrowf.conductor:main:387 - ERROR - ("time data '' does not match format '%H:%M:%S'",)
Traceback (most recent call last):
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/conductor.py", line 382, in main
    completion_status = conductor.monitor_study()
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/conductor.py", line 352, in monitor_study
    completion_status = dag.execute_ready_steps()
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/datastructures/core/executiongraph.py", line 870, in execute_ready_steps
    self._execute_record(_record, adapter)
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/datastructures/core/executiongraph.py", line 565, in _execute_record
    retcode = record.execute(adapter)
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/datastructures/core/executiongraph.py", line 95, in execute
    retcode, jobid = self._execute(adapter, self.script)
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/datastructures/core/executiongraph.py", line 125, in _execute
    self.step, script, self.workspace.value)
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/interfaces/script/fluxscriptadapter.py", line 650, in submit
    job_name=step.name, force_broker=force_broker
  File "/g/g17/mast2/.local/lib/python3.6/site-packages/maestrowf-1.1.9.dev0-py3.6.egg/maestrowf/interfaces/script/_flux/flux0_18_0.py", line 94, in submit
    seconds = datetime.strptime(walltime, "%H:%M:%S")
  File "/usr/mic/bio/anaconda3/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/mic/bio/anaconda3/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%H:%M:%S'

**Comment by FrankD412** [comment]
@Jmast -- this is an improperly formatted time string win the `walltime` key. I thought that the validation fixed this, so I'll have to take a second look.
