### ISSUE TITLE
Crash Log Traceback stuck at localscriptadapter.py

### ISSUE THREAD

**Issue by faical-yannick-congo** [LLNL/maestrowf#49]
When i run a study and a step fails i have in the stderr trace in the .txt file but it is stuck at localscriptadapter.py. Here is a trace for SEM-Images-Stats.txt.
------
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138
Traceback (most recent call last):
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/fyc/anaconda2/envs/demo-2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file localscriptadapter.py, line 138

**Comment by FrankD412** [comment]
Confirmed -- It looks like this was my mistake. I'm trying to cast an Exception to a string and that can't be done.
